[pytest]
markers =
    task_api: to run tests for TaskApi
addopts = -rA
          --alluredir allure-results
          --clean-alluredir
          -n 5
          --maxprocesses=5
log_format = %(levelname)s [%(asctime)s] %(filename)s:%(lineno)d %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
log_level = 20
